### PR TITLE
feat: Deprecate tslint and eslint all the things.

### PR DESCRIPTION
**Pull request by beausmith**
Replace tslint with eslint, stylelint, commitlint, etc. 

Sync'd with BAS linting, etc.

### CODE REVIEW

**Comment by beausmith** [comment]
Yes, I agree. It's a little pre-optimized. Let's discuss and fix it.

**Comment by benadida** [comment]
I can live with it if there is no obvious easier path.

**Comment by beausmith** [comment]
I've removed commitlint and will merge this without a commit linter for now.

**Comment by beausmith** [comment]
Captured here: https://github.com/votingworks/bmd/issues/338

**Pull request merged**
