### PR TITLE
Anywhere ballot styles

### LINKED ISSUE #45: Update to Anywhere Ballot design

### LINKED ISSUE #46: Return to QR Code Screen after printing.
- [ ] https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onafterprint

### PR DESCRIPTION
**Pull request by beausmith**
Partial application of Anywhere ballot styles.

Please look over to see if there are any styles to add other than what is left to do in "Milestone 1".

Resolves #45 
Resolves #46

### CODE REVIEW

**Comment by beausmith** [comment]
I have an idea why tests didn't pass on CI and did locally.

Test drive or branch app and I'll fix tests before merging.

**Comment by benadida** [comment]
one more issue: on the review screen there are two buttons in the top navbar, one says `go back`, the other says `back`. I imagine we want only one of those.

**Comment by beausmith** [comment]
@benadida - Please re-review.

Not sure how… but there were some snapshots which needed to be updated. 

I have…

- Updated the snapshots.
- Removed extra "Go Back" button (which was there for testing, but that I forgot to remove before committing… D'oh!)

**Comment by benadida** [comment]
@beausmith I'm still seeing the print-preview showing the "are you sure" screen rather than the actual ballot to print.

**Comment by beausmith** [comment]
@benadida - Sorry, just ran into that myself. Sorry I overlooked that error. I'm on it.

**Comment by beausmith** [comment]
@benadida - Please re-review. Fixed the modal-printing issue. Also styled the modals to be more pretty. And a couple other minor tweaks.

**Comment by benadida** [comment]
lgtm!

**Pull request merged**
